LABEL version="1.0.0" description="Servidor TCP | Rebertty Macedo da Silva" maintainer="Edilayne Salgueiro <edilayne@dcomp.ufs.br>"

FROM python:3-slim

WORKDIR /usr/src/tcpcapital

COPY . .

EXPOSE 12000

CMD [ "python3", "./TCPServer.py" ]
